language: node_js
cache:
  yarn: true
  directories:
  - ~/.npm
notifications:
  email: false
jobs:
  include:
  - stage: release
    node_js: stable
    deploy:
      before_install: npm install -g greenkeeper-lockfile
      provider: script
      skip_cleanup: true
      script:
        - npm run semantic-release
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
script:
  - yarn test
